name: QPM build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  qpm_info:
    runs-on: ubuntu-latest

    outputs:
      name: ${{ steps.read_qpm_info.outputs.name }}
      id: ${{ steps.read_qpm_info.outputs.id }}
      override_so_name: ${{ steps.read_qpm_info.outputs.override_so_name }}
      qmod_output_path: ${{ steps.read_qpm_info.outputs.qmod_output_path }}
      ndk: ${{ steps.read_qpm_info.outputs.ndk }}
      dependencies_dir: ${{ steps.read_qpm_info.outputs.dependencies_dir }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true
          fetch-depth: 0
          fetch-tags: true

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Read info from qpm.json
        id: read_qpm_info
        run: |
          NAME="$(jq -r '.info.name' qpm.json)"
          ID="$(jq -r '.info.id' qpm.json)"
          OVERRIDE_SO_NAME="$(jq -r '.info.additionalData.overrideSoName' qpm.json)"
          QMOD_OUTPUT_PATH="$(jq -r '.workspace.qmodOutput' qpm.json)"
          NDK="$(jq -r '.workspace.ndk' qpm.json)"
          DEPENDENCIES_DIR="$(jq -r '.dependenciesDir' qpm.json)"

          echo "name=${NAME}" | tee -a "$GITHUB_OUTPUT"
          echo "id=${ID}" | tee -a "$GITHUB_OUTPUT"
          echo "override_so_name=${OVERRIDE_SO_NAME}" | tee -a "$GITHUB_OUTPUT"
          echo "qmod_output_path=${QMOD_OUTPUT_PATH}" | tee -a "$GITHUB_OUTPUT"
          echo "ndk=${NDK}" | tee -a "$GITHUB_OUTPUT"
          echo "dependencies_dir=${DEPENDENCIES_DIR}" | tee -a "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: qpm_info
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          submodules: true
          lfs: true
          fetch-depth: 0
          fetch-tags: true

      - uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Get home path
        run: |
          echo "HOME=$HOME" | tee -a "$GITHUB_ENV"

      - name: Extract version
        if: startsWith(github.ref, 'refs/tags/v')
        id: version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          FULL_VERSION="${GITHUB_REF#refs/tags/v}"
          VERSION="${FULL_VERSION%%[-+]*}"

          echo "TAG=$TAG" | tee -a "$GITHUB_OUTPUT"
          echo "VERSION=$VERSION" | tee -a "$GITHUB_OUTPUT"
          echo "FULL_VERSION=$FULL_VERSION" | tee -a "$GITHUB_OUTPUT"

      - name: Update version in qpm.json, qpm.shared.json, and mod.template.json
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Update qpm.json
          if [ -f qpm.json ]; then
            MODIFIED_JSON="$(jq --arg version "$VERSION" '.info.version = $version' qpm.json)"
            echo "$MODIFIED_JSON" > qpm.json
          fi

          # Update qpm.shared.json if it exists
          if [ -f qpm.shared.json ]; then
            MODIFIED_JSON="$(jq --arg version "$VERSION" '.config.info.version = $version' qpm.shared.json)"
            echo "$MODIFIED_JSON" > qpm.shared.json
          fi

          # Update mod.template.json if it exists
          if [ -f mod.template.json ]; then
            MODIFIED_JSON="$(jq --arg version "$FULL_VERSION" '.version = $version' mod.template.json)"
            echo "$MODIFIED_JSON" > mod.template.json
          fi
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
          FULL_VERSION: ${{ steps.version.outputs.FULL_VERSION }}

      - name: Create dependencies directory
        run: |
          mkdir -p "${{ needs.qpm_info.outputs.dependencies_dir }}"

      - name: Setup qpm
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: Fernthedev/qpm-action@v1
        with:
          workflow_token: ${{ secrets.GITHUB_TOKEN }}
          restore: false
          resolve_ndk: true
          cache: false

      - name: Setup qpm for release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: Fernthedev/qpm-action@v1
        with:
          cache: false
          publish_token: ${{ secrets.QPM_TOKEN }}
          publish: late
          qpm_debug_bin: false
          qpm_release_bin: true
          resolve_ndk: true
          restore: false
          tag: ${{ steps.version.outputs.TAG }}
          version: ${{ steps.version.outputs.VERSION }}
          workflow_token: ${{ github.token }}

      - name: Build
        run: |
          qpm restore
          qpm s build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          if-no-files-found: error
          path: |
            ./build/${{ needs.qpm_info.outputs.override_so_name }}

  release:
    runs-on: ubuntu-latest
    needs: [qpm_info, build]
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: output/

      - name: Generate release body
        run: |
          BODY_FILE="body.txt"
          echo '---' >> body.txt
          echo '' >> body.txt
          echo '### Checksums' >> body.txt
          echo '' >> body.txt
          echo '```' >> body.txt
          (cd output && sha256sum *) >> body.txt
          echo '```' >> body.txt

      - name: Upload .a artifacts
        id: upload_file_so
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./output/*.a
          body_path: body.txt
          generate_release_notes: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
